name: Build and deploy

on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  build:
    name: Build (cron + webhook)
    runs-on: ubuntu-24.04

    env:
      REGISTRY: ghcr.io
      REPO: ${{ github.repository }}
      VERSION: ${{ github.ref_name }} # "main" or "v0.1.0"

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v6
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build webhook (no AWS)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          target: webhook
          build-args: |
            AWS_ENABLED=false
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.REPO }}:webhook-${{ env.VERSION }}
          platforms: |
            linux/amd64
            linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build webhook (AWS)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          target: webhook
          build-args: |
            AWS_ENABLED=true
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.REPO }}:webhook-aws-${{ env.VERSION }}
          platforms: |
            linux/amd64
            linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build cron (no AWS)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          target: cron
          build-args: |
            AWS_ENABLED=false
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.REPO }}:cron-${{ env.VERSION }}
          platforms: |
            linux/amd64
            linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build cron (AWS)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          target: cron
          build-args: |
            AWS_ENABLED=true
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.REPO }}:cron-aws-${{ env.VERSION }}
          platforms: |
            linux/amd64
            linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
